### ISSUE TITLE
Valid drop frame values fail to parse

### ISSUE THREAD

**Issue by dceddia** [opencinemac/vtc-rs#7]
Hello! Thank you for creating this library, it's been a huge help. I ran into an issue where drop frame values are failing to parse when they're too few frames beyond a minute boundary. So for instance, `20:22:47;02` in 59.94DF should be fine, but that failed with `drop-frame tc cannot have a frames value of less than 4 on minutes not divisible by 10, found '2'`.

It looks like the `drop_frame_tc_adjustment` function is checking for multiples of 10 minutes when doing this check, but it didn't look at the `seconds` value.

I made a pull request here with a fix: https://github.com/opencinemac/vtc-rs/pull/6 (and no rush, I'm operating off my fork in the meantime)

**Comment by peake100** [comment]
Hello!

Thanks for filling this issue. I've already left a comment on the PR but just wanted to comment here as well and say thanks for using the lib!

**Comment by peake100** [comment]
Fixed by #11
